@server_HostAddress = http://localhost:5043
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJjaGlkb3ppZS5kLm53YW5nd3VAZ21haWwuY29tIiwiZXhwIjoxNzcxOTIyNTk3LCJpc3MiOiJ0b2RvLWFwaSIsImF1ZCI6InRvZG8tYXBpIn0.9tAGCutpMZOBKNvqiWn2v_Lb0mAoO3QFk9ltTR-2beA

### Register
POST {{server_HostAddress}}/register
Content-Type: application/json

{
    "Name": "Chidozie Nwangwu",
    "Email": "chidozie.d.nwangwu@gmail.com",
    "Password": "HookedOnFlays2949"
}

### Login
POST {{server_HostAddress}}/login
Content-Type: application/json

{
    "Email": "chidozie.d.nwangwu@gmail.com",
    "Password": "HookedOnFlays2949"
}

### Get User (protected)
GET {{server_HostAddress}}/Users/3
Authorization: Bearer {{token}}

### Create Todo (protected)
POST {{server_HostAddress}}/todos
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Title": "Finish JWT implementation",
    "Description": "Wire up the middleware"
}

### Get Todos (protected)
GET {{server_HostAddress}}/todos?page=1&limit=10
Authorization: Bearer {{token}}