@server_HostAddress = http://localhost:5043

GET {{server_HostAddress}}/
Accept: application/json

###

POST {{server_HostAddress}}/api/auth/register
Content-Type: application/json

{
    "Name": "CJ Nwangwu",
    "Email": "captainnwangwu@gmail.com",
    "Password": "CodingRocks247!"
}
### 
POST {{server_HostAddress}}/api/Auth/register
Content-Type: application/json

{
    "Name": "Chido Nwangwu",
    "Email": "chido247@gmail.com",
    "Password": "USAfrica247"
}

### 
POST {{server_HostAddress}}/api/Auth/login
Content-Type: application/json

{
    "Email": "chido247@gmail.com",
    "Password": "USAfrica247"
}

### 
POST {{server_HostAddress}}/api/Auth/login
Content-Type: application/json

{
    "Email": "captainnwangwu@gmail.com",
    "Password": "CodingRocks247"
}

###
GET {{server_HostAddress}}/api/Users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJjaGlkbzI0N0BnbWFpbC5jb20iLCJleHAiOjE3NzE3ODI0NzgsImlzcyI6InRvZG8tYXBpIiwiYXVkIjoidG9kby1hcGkifQ.OdAc-Fkzp4N8ddwKc45-4Fvf2fx25QudqZxTc1ZgArM
###