@server_HostAddress = http://localhost:5043

GET {{server_HostAddress}}/
Accept: application/json

###

POST {{server_HostAddress}}/api/auth/register
Content-Type: application/json

{
    "Name": "CJ Nwangwu",
    "Email": "captainnwangwu@gmail.com",
    "Password": "CodingRocks247!"
}

###